// <auto-generated />
namespace EFMigrations.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Make_Model_Relationship_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_Model_Relationship_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201906251440389_Make_Model_Relationship_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
